ALTER TABLE purchases ADD COLUMN IF NOT EXISTS purchase_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS due_amount NUMERIC(15,2) NOT NULL DEFAULT 0;
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid';
ALTER TABLE purchase_items ADD COLUMN IF NOT EXISTS line_number INT;
NOTIFY pgrst, 'reload schema';
